import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { test } from "node:test";

test("Godot 4 project is the playable client", () => {
  const proj = readFileSync("godot/project.godot", "utf8");
  assert.match(proj, /config\/features=PackedStringArray\("4\.3"/);
  assert.match(proj, /default_texture_filter=1/);
  assert.match(proj, /run\/main_scene="res:\/\/scenes\/main\.tscn"/);
  assert.ok(existsSync("godot/scenes/main.tscn"));
  assert.ok(existsSync("godot/scripts/net.gd"));
  assert.ok(existsSync("godot/assets/art/char-warm.png"));
  assert.ok(existsSync("godot/assets/art/char-pine.png"));
  assert.ok(existsSync("godot/assets/art/tex-grass.png"));
  const charter = readFileSync("docs/CHARTER.md", "utf8");
  assert.match(charter, /引擎已定为 Godot 4/);
  assert.match(charter, /不再等网页打磨/);
  assert.match(charter, /不用 Unity/);
  assert.match(charter, /开间/);
  assert.match(charter, /进谷/);
  assert.match(charter, /钓矿厨出谷砧摊田卦睡/);
  assert.match(charter, /双人规则/);
  assert.match(charter, /薄声音/);
  assert.match(charter, /P0 网页一晚在 Godot 上成立/);
  assert.match(charter, /观感打磨 \+ 两机实玩/);
  assert.match(charter, /然后才 iOS/);
  assert.doesNotMatch(charter, /Capacitor/);
  assert.doesNotMatch(charter, /正在迁/);
});

test("Godot HTML5 export is what phones open", () => {
  assert.ok(existsSync("godot/export/web/index.html"));
  const html = readFileSync("godot/export/web/index.html", "utf8");
  assert.match(html, /并肩山谷/);
  assert.match(html, /<canvas/);
  assert.match(html, /Engine/);
  assert.doesNotMatch(html, /\$GODOT_/);
  assert.ok(existsSync("godot/export/web/index.wasm"));
  assert.ok(existsSync("godot/export/web/index.pck"));
  assert.ok(existsSync("godot/export/web/index.js"));
});

test("Valley look is one dusk illustration, not DST stickers", () => {
  assert.ok(existsSync("godot/fonts/kai.ttf"));
  assert.ok(existsSync("godot/assets/art/cover-valley.png"));
  assert.ok(existsSync("godot/assets/art/bed-valley.png"));
  assert.ok(existsSync("godot/scenes/valley.tscn"));
  assert.ok(existsSync("godot/scenes/play.tscn"));
  assert.ok(existsSync("godot/scripts/valley_world.gd"));
  assert.ok(existsSync("godot/scripts/valley_logic.gd"));
  assert.ok(!existsSync("godot/scripts/valley_map.gd"));
  const bedPng = readFileSync("godot/assets/art/bed-valley.png");
  assert.equal(bedPng[0], 0x89);
  assert.equal(bedPng.readUInt32BE(16), 1224);
  assert.equal(bedPng.readUInt32BE(20), 612);
  const app = readFileSync("godot/scripts/app.gd", "utf8");
  assert.match(app, /scenes\/play\.tscn/);
  const playScene = readFileSync("godot/scenes/play.tscn", "utf8");
  assert.match(playScene, /scripts\/play\.gd/);
  const valleyScene = readFileSync("godot/scenes/valley.tscn", "utf8");
  assert.match(valleyScene, /bed-valley\.png/);
  assert.match(valleyScene, /valley_world\.gd/);
  assert.match(valleyScene, /valley_logic\.gd/);
  assert.doesNotMatch(valleyScene, /prop-cover-|prop-hut|prop-lodge/);
  assert.ok(existsSync("godot/assets/art/ground-valley.png"));
  const look = readFileSync("godot/scripts/look.gd", "utf8");
  assert.match(look, /kai\.ttf/);
  assert.match(look, /multiply\.ttf/);
  assert.match(look, /tex-plaque/);
  assert.match(look, /contact\(/);
  assert.match(look, /sit_frac/);
  assert.match(look, /person_mat/);
  assert.match(look, /const BODY := 128/);
  assert.match(look, /const FOOT := 0\.979/);
  assert.match(look, /SHADOW_EAST/);
  assert.match(look, /func air_mat/);
  assert.match(look, /func air_layer/);
  assert.match(look, /air\.gdshader/);
  assert.match(look, /Sprite2D/);
  assert.ok(existsSync("godot/shaders/air.gdshader"));
  assert.ok(existsSync("godot/docs/ART.md"));
  const artDoc = readFileSync("godot/docs/ART.md", "utf8");
  assert.match(artDoc, /色温/);
  assert.match(artDoc, /西 \/ 左|西\/左/);
  assert.match(artDoc, /描边/);
  assert.match(artDoc, /脚影/);
  assert.match(artDoc, /禁止混包/);
  assert.match(artDoc, /SHADOW_EAST/);
  assert.match(artDoc, /没有精神值/);
  assert.doesNotMatch(artDoc, /Kenney|itch\.io/);
  assert.match(look, /name_box/);
  assert.match(look, /func slip_box/);
  assert.match(look, /func chip_button/);
  assert.match(look, /tex-slip/);
  assert.match(look, /AXIS_STRETCH_MODE_TILE_FIT/);
  assert.doesNotMatch(look, /func slip_box\(\)[\s\S]{0,400}tex-plaque/);
  assert.ok(existsSync("godot/assets/art/tex-slip.png"));
  const paintSlip = readFileSync("tools/paint_hud_slip.py", "utf8");
  assert.match(paintSlip, /prop-cabin/);
  assert.match(paintSlip, /tex-paper/);
  assert.match(paintSlip, /tex-slip/);
  assert.match(paintSlip, /HUD wood/);
  assert.match(paintSlip, /tex-plaque/);
  assert.match(paintSlip, /640, 80/);
  assert.match(paintSlip, /360, 180/);
  assert.doesNotMatch(paintSlip, /floor-valley|cover-valley|ground-valley/);
  assert.doesNotMatch(paintSlip, /Wilson|Don't Starve|Dont Starve/i);
  assert.match(look, /set_shader_parameter\("grade", 0\.0\)/);
  assert.match(look, /VALLEY_DUSK/);
  assert.match(look, /1\.0, 1\.0, 1\.0/);
  assert.doesNotMatch(look, /SystemFont/);
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /_clamp_cam/);
  assert.match(play, /_cam_locked/);
  assert.match(play, /%s×%s/);
  assert.match(play, /1\.0, 1\.0, 1\.0/);
  assert.match(play, /VALLEY_DUSK/);
  assert.match(play, /air_layer/);
  assert.match(play, /日 %s · %s · %s · 金 %s/);
  assert.doesNotMatch(play, /饿/);
  assert.doesNotMatch(play, /魂/);
  assert.doesNotMatch(play, /sanity|Sanity/);
  assert.doesNotMatch(play, /s\.get\("hp"/);
  assert.doesNotMatch(play, /s\.get\("hunger"/);
  assert.ok(existsSync("godot/fonts/multiply.ttf"));
  const actor = readFileSync("godot/scripts/actor_view.gd", "utf8");
  assert.match(actor, /CanvasLayer/);
  assert.match(actor, /_place_name/);
  assert.match(actor, /person_mat/);
  assert.match(actor, /Look\.BODY/);
  assert.match(actor, /Look\.FOOT/);
  assert.match(actor, /Look\.BODY - 28/);
  assert.match(actor, /SHADOW_EAST/);
  assert.doesNotMatch(actor, /var h := 48/);
  const lookShot = readFileSync("godot/scripts/headless_look.gd", "utf8");
  assert.match(lookShot, /cabin-pair/);
  assert.match(lookShot, /set_moving/);
  assert.match(lookShot, /chip_button/);
  assert.match(lookShot, /slip_box/);
  assert.match(lookShot, /VALLEY_DUSK/);
  assert.match(lookShot, /air_layer/);
  assert.match(lookShot, /山谷/);
  assert.match(lookShot, /日 0 · 春 · 白天 · 金 20/);
  assert.match(lookShot, /_shot\("fish"\)/);
  assert.match(lookShot, /busy": "fish"/);
  assert.doesNotMatch(lookShot, /魂|饿/);
  const boot = readFileSync("godot/scripts/boot.gd", "utf8");
  assert.match(boot, /cover-valley/);
  assert.doesNotMatch(boot, /prop-cabin|prop-inn|Wanderer/);
  const room = readFileSync("godot/scripts/room.gd", "utf8");
  assert.match(room, /cover-valley/);
  assert.doesNotMatch(room, /char-warm|char-pine|Wanderer/);
  const valley = readFileSync("godot/scripts/valley_world.gd", "utf8");
  const logic = readFileSync("godot/scripts/valley_logic.gd", "utf8");
  const playSrc = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(valley, /bed-valley\.png/);
  assert.match(valley, /VALLEY_DUSK/);
  assert.match(valley, /class_name ValleyWorld/);
  assert.match(logic, /class_name ValleyLogic/);
  assert.match(logic, /show_crops/);
  assert.match(playSrc, /scenes\/valley\.tscn/);
  assert.match(playSrc, /ValleyWorld/);
  assert.doesNotMatch(valley, /prop-cover-tree|prop-cover-lamp|prop-cover-shore|prop-cover-verge|prop-hut|prop-lodge/);
  assert.doesNotMatch(logic, /prop-cover-tree|prop-cover-lamp|prop-cover-shore|prop-cover-verge|prop-hut|prop-lodge/);
  assert.doesNotMatch(logic, /Look\.hung/);
  assert.doesNotMatch(playSrc, /prop-cover-tree|prop-hut\.png|prop-lodge\.png/);
  assert.match(playSrc, /_tiles\.is_empty\(\) or _zone == "valley"/);
  assert.doesNotMatch(valley, /prop-mine\.png/);
  assert.doesNotMatch(valley, /prop-stall\.png/);
  assert.doesNotMatch(valley, /prop-anvil\.png/);
  assert.doesNotMatch(valley, /prop-altar\.png/);
  assert.doesNotMatch(valley, /prop-board\.png/);
  assert.doesNotMatch(valley, /prop-pine\.png/);
  assert.doesNotMatch(valley, /prop-tree-gold/);
  assert.doesNotMatch(valley, /prop-tree\.png/);
  assert.doesNotMatch(valley, /prop-dock\.png/);
  assert.doesNotMatch(valley, /prop-gate\.png/);
  assert.doesNotMatch(logic, /prop-stall\.png|prop-anvil\.png|prop-pine\.png|prop-tree\.png/);
  const unify = readFileSync("tools/unify_dusk.py", "utf8");
  assert.match(unify, /cover-valley/);
  assert.match(unify, /quiet_scrub/);
  assert.doesNotMatch(unify, /scrub_inn/);
  assert.match(unify, /prop-hut/);
  assert.match(unify, /prop-lodge/);
  assert.match(unify, /prop-cover-tree/);
  assert.match(unify, /prop-cover-lamp/);
  assert.match(unify, /prop-cover-shore/);
  assert.match(unify, /Does not touch the cover/);
  assert.match(unify, /60, 310, 260, 550/);
  assert.match(unify, /840, 190, 1180, 510/);
  assert.match(unify, /0, 168, 90, 338/);
  assert.match(unify, /0, 140, 100, 308/);
  assert.match(unify, /0, 48, 150, 328/);
  assert.match(unify, /705, 255, 885, 465/);
  assert.match(unify, /0, 140, 140, 340/);
  assert.match(unify, /TREE_DENSE/);
  assert.match(unify, /HUT_POLY/);
  assert.match(unify, /LODGE_POLY/);
  assert.match(unify, /1195, 105, 1280, 190/);
  assert.match(unify, /cut_tree/);
  assert.match(unify, /918, 298, 972, 372/);
  assert.match(unify, /1008, 548, 1148, 668/);
  assert.match(unify, /fade_bank/);
  assert.match(unify, /cut_house/);
  assert.match(unify, /eat_gold_sky/);
  assert.match(unify, /kill_haze/);
  assert.doesNotMatch(unify, /Wilson|Don't Starve|Dont Starve/i);
  assert.ok(existsSync("godot/assets/art/prop-cover-tree.png"));
  assert.ok(existsSync("godot/assets/art/prop-cover-tree-b.png"));
  assert.ok(existsSync("godot/assets/art/prop-cover-lamp.png"));
  assert.ok(existsSync("godot/assets/art/prop-cover-shore.png"));
  assert.ok(existsSync("godot/assets/art/prop-cover-verge.png"));
  assert.ok(existsSync("godot/assets/art/prop-hut.png"));
  assert.ok(existsSync("godot/assets/art/prop-lodge.png"));
  const oneLang = readFileSync("tools/paint_one_language.py", "utf8");
  assert.match(oneLang, /Does not touch the cover/);
  assert.match(oneLang, /prop-tree/);
  assert.match(oneLang, /prop-cabin/);
  assert.match(oneLang, /tex-paper/);
  assert.match(oneLang, /prop-bush/);
  assert.match(oneLang, /prop-tuft/);
  assert.match(oneLang, /prop-rock/);
  assert.match(oneLang, /prop-board/);
  assert.match(oneLang, /prop-stall/);
  assert.match(oneLang, /prop-fire/);
  assert.match(oneLang, /prop-gate/);
  assert.doesNotMatch(oneLang, /cover-valley/);
  assert.doesNotMatch(oneLang, /Wilson|Don't Starve|Dont Starve/i);
  const sitMain = readFileSync("tools/paint_valley_sit.py", "utf8");
  assert.match(sitMain, /Roofs are unify_dusk/);
  assert.doesNotMatch(sitMain, /save\(paint_house\("hut"\)/);
  const bedPaint = readFileSync("tools/paint_valley_bed.py", "utf8");
  assert.match(bedPaint, /Does not touch the cover/);
  assert.match(bedPaint, /bed-valley/);
  assert.match(bedPaint, /CROP_Y0 = 302/);
  assert.match(bedPaint, /PATH_LO, PATH_HI/);
  assert.match(bedPaint, /valley-path-fill/);
  assert.match(bedPaint, /CORRIDOR_X0, CORRIDOR_X1/);
  assert.ok(existsSync("tools/ref/valley-path-fill.png"));
  assert.doesNotMatch(bedPaint, /save\(.*cover-valley/);
  assert.doesNotMatch(bedPaint, /resize\(\(x1 - x0/);
  assert.doesNotMatch(valley, /floor-valley|ground-valley|_bend\(/);
  assert.doesNotMatch(valley, /band-river|band-path|band-meadow/);
  const floorPaint = readFileSync("tools/paint_valley_sit.py", "utf8");
  assert.match(floorPaint, /308\.0 \+ fx \* 82\.0/);
  assert.match(floorPaint, /0\.36, 0\.38, 0\.28/);
  assert.match(floorPaint, /1\.00, 0\.98, 0\.88/);
  assert.match(floorPaint, /Do not move the path or creek/);
  assert.match(floorPaint, /short wet lip|thin wet lip/);
  assert.doesNotMatch(floorPaint, /g \/ np\.maximum\(g\.max/);
  assert.ok(existsSync("godot/assets/art/floor-valley.png"));
  assert.doesNotMatch(valley, /_tile\(/);
  assert.doesNotMatch(valley, /prop-cabin|prop-inn/);
  assert.doesNotMatch(play, /modulate = Color\(1, 1, 1, 0\.55\)/);
  const scripts = ["boot.gd", "room.gd", "play.gd", "look.gd", "valley_world.gd", "valley_logic.gd", "actor_view.gd", "ear.gd"]
    .map((n) => readFileSync(`godot/scripts/${n}`, "utf8"))
    .join("\n");
  assert.doesNotMatch(scripts, /Wanderer|Wilson|Don't Starve|Dont Starve/i);
  const inn = readFileSync("godot/assets/art/prop-inn.png");
  assert.ok(!inn.includes("Wanderer") && !inn.includes("WANDERER") && !inn.includes("Good Ale"));
  assert.ok(existsSync("godot/assets/art/prop-anvil.png"));
  assert.ok(existsSync("godot/assets/art/prop-altar.png"));
  const sync = readFileSync("godot/tools/sync_art.sh", "utf8");
  assert.match(sync, /keeping godot\/assets\/art/);
  assert.doesNotMatch(sync, /cp -a/);
  const paint = readFileSync("tools/paint_look.py", "utf8");
  assert.match(paint, /trim_empty_feet/);
  assert.match(paint, /def finish_sit_props/);
  const sit = readFileSync("tools/sit_chars.py", "utf8");
  assert.match(sit, /char-warm-ref/);
  assert.match(sit, /FOOT_Y/);
  assert.match(sit, /BAN/);
  assert.doesNotMatch(sit, /SRCS\[.*= .*walk-raw/);
  const warmWalk = readFileSync("godot/assets/art/char-warm-walk.png");
  assert.ok(!warmWalk.includes("Wilson") && !warmWalk.includes("WANDERER"));
});

test("Godot client plays fish, mine and kitchen from the same snap", () => {
  assert.ok(existsSync("godot/scripts/zone_map.gd"));
  assert.ok(existsSync("godot/scripts/headless_loop.gd"));
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /toasts/);
  assert.match(play, /send_take/);
  assert.match(play, /_bag_sig/);
  assert.match(play, /chip_button/);
  assert.match(play, /slip_box/);
  assert.match(play, /_prompt_bar/);
  assert.match(play, /580, 64/);
  assert.doesNotMatch(play, /StyleBoxFlat/);
  assert.doesNotMatch(play, /wood_button\(label/);
  assert.match(play, /_ink_n/);
  assert.match(play, /_paint_fish/);
  assert.match(play, /_fish_mark\.position\.x = 16 \+ 528\.0 \* mark/);
  assert.match(play, /_valley\.visible = zone == "valley"/);
  assert.match(play, /_zone_map\.visible = indoor/);
  assert.match(play, /Look\.MOSS/);
  assert.match(play, /_tiles = \[\]/);
  assert.match(play, /show_fog/);
  assert.match(play, /biome/);
  assert.match(play, /fires/);
  const actor = readFileSync("godot/scripts/actor_view.gd", "utf8");
  assert.match(actor, /fishMark|fish_mark/);
  assert.match(actor, /char-%s-fish/);
  assert.match(actor, /Look\.MOSS/);
  assert.match(actor, /_bar_pull/);
  const look = readFileSync("godot/scripts/look.gd", "utf8");
  assert.match(look, /const MOSS/);
  const zone = readFileSync("godot/scripts/zone_map.gd", "utf8");
  assert.match(zone, /ch == "#"/);
  assert.match(zone, /func _wall/);
  assert.match(zone, /tex-wood\.png/);
  assert.match(zone, /tex-stone\.png/);
  assert.match(zone, /show_fog/);
  assert.match(zone, /ch == "F"/);
  assert.match(zone, /ch == "J"/);
  assert.doesNotMatch(zone, /ColorRect\.new\(\)[\s\S]{0,80}ch == "#"/);
  const net = readFileSync("godot/scripts/net.gd", "utf8");
  assert.match(net, /revealed/);
  const world = readFileSync("src/sim/world.ts", "utf8");
  assert.match(world, /先面向要做的事/);
  assert.match(world, /先面向树、火或能砍的/);
  assert.match(world, /手里没有能切的/);
  assert.doesNotMatch(world, /if \(!p\.input\.held\) return;/);
  const loop = readFileSync("godot/scripts/headless_loop.gd", "utf8");
  assert.match(loop, /FISH_OK/);
  assert.match(loop, /ORE_OK/);
  assert.match(loop, /PLATE_OK/);
  assert.ok(existsSync("godot/scripts/headless_cover_loop.gd"));
  const coverLoop = readFileSync("godot/scripts/headless_cover_loop.gd", "utf8");
  assert.match(coverLoop, /COVER_LOOP_OK/);
  assert.match(coverLoop, /show_room|开一间/);
  assert.match(coverLoop, /SHOW_ROOM/);
  assert.match(coverLoop, /if ore_ok:/);
  assert.match(coverLoop, /PLAY_ZONE_VALLEY/);
  assert.match(coverLoop, /PLAY_ZONE_MINE/);
  assert.match(coverLoop, /PLAY_ZONE_KITCHEN/);
  assert.match(coverLoop, /PLAY_FISH_MARK/);
  assert.match(coverLoop, /_note_play/);
  assert.ok(existsSync("godot/scripts/headless_play_evening.gd"));
  assert.ok(existsSync("godot/scenes/play_evening.tscn"));
  const playEveningScene = readFileSync("godot/scenes/play_evening.tscn", "utf8");
  assert.match(playEveningScene, /headless_play_evening\.gd/);
  const playEvening = readFileSync("godot/scripts/headless_play_evening.gd", "utf8");
  assert.match(playEvening, /scenes\/play\.tscn/);
  assert.match(playEvening, /_on_snap/);
  assert.match(playEvening, /PLAY_ZONE_VALLEY/);
  assert.match(playEvening, /PLAY_ZONE_MINE/);
  assert.match(playEvening, /PLAY_ZONE_KITCHEN/);
  assert.match(playEvening, /PLAY_FISH_MARK/);
  assert.match(playEvening, /PLAY_EVENING_OK/);
  assert.match(playEvening, /bed-valley\.png/);
  assert.match(playEvening, /fishMark/);
  assert.match(playEvening, /_fish_mark/);
  assert.match(playEvening, /528\.0 \* mark/);
  assert.doesNotMatch(playEvening, /魂|Wilson|Don't Starve|Dont Starve/i);
  assert.match(loop, /if ore_ok:/);
  assert.match(loop, /send_acc/);
  assert.match(loop, /quit\(0\)[\s\S]{0,20}return/);
  assert.ok(existsSync("godot/scripts/headless_rest_loop.gd"));
  const rest = readFileSync("godot/scripts/headless_rest_loop.gd", "utf8");
  assert.match(rest, /WILD_OK/);
  assert.match(rest, /FORGE_OK/);
  assert.match(rest, /STALL_OK/);
  assert.doesNotMatch(rest, /Wilson|Don't Starve|Dont Starve/i);
  assert.ok(existsSync("godot/scripts/headless_village_loop.gd"));
  const village = readFileSync("godot/scripts/headless_village_loop.gd", "utf8");
  assert.match(village, /FIELD_OK/);
  assert.match(village, /FORTUNE_OK/);
  assert.match(village, /BOARD_OK/);
  assert.match(village, /DAY_REST_NO/);
  assert.match(village, /SLEEP_OK/);
  assert.match(village, /HARVEST_OK/);
  assert.match(village, /show_crops/);
  assert.doesNotMatch(village, /Wilson|Don't Starve|Dont Starve/i);
  assert.doesNotMatch(village, /waitingFortune|另一部手机/);
});

test("Godot village shows crops, fortune and the dawn board from the same snap", () => {
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /_paint_signs/);
  assert.match(play, /_paint_crops/);
  assert.match(play, /show_crops/);
  assert.match(play, /今晚/);
  assert.match(play, /fortune/);
  assert.match(play, /熟了/);
  assert.doesNotMatch(play, /waitingFortune/);
  assert.doesNotMatch(play, /另一部手机|必须两/);
  const valley = readFileSync("godot/scripts/valley_logic.gd", "utf8");
  assert.match(valley, /show_crops/);
  assert.match(valley, /prop-tuft|prop-bush/);
  assert.doesNotMatch(valley, /Look\.hung/);
  assert.doesNotMatch(valley, /add_child\(_crop_at/);
  assert.doesNotMatch(valley, /prop-cabin|prop-inn/);
  assert.match(play, /_zone == "valley"/);
  assert.match(play, /_atlas\.visible = false/);
  const world = readFileSync("src/sim/world.ts", "utf8");
  assert.match(world, /没有种。田不用浇/);
  assert.match(world, /也得对着铺/);
  assert.match(world, /还早。天黑再歇/);
  assert.match(world, /一个人能问|问今日/);
});

test("Cover-coat people walk and act on the painted bed", () => {
  const actor = readFileSync("godot/scripts/actor_view.gd", "utf8");
  assert.match(actor, /char-%s/);
  assert.match(actor, /warm" if warm else "pine/);
  assert.match(actor, /const BODY := 128|Look\.BODY/);
  assert.match(actor, /Look\.FOOT/);
  assert.match(actor, /SHADOW_EAST/);
  assert.doesNotMatch(actor, /Wilson|Don't Starve|Dont Starve|Wanderer/i);
  const look = readFileSync("godot/scripts/look.gd", "utf8");
  assert.match(look, /const BODY := 128/);
  assert.match(look, /const FOOT := 0\.979/);
  assert.match(look, /const SHADOW_EAST/);
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /Net\.send_input/);
  assert.match(play, /wood_button\("做"/);
  assert.match(play, /wood_button\("喊"/);
  assert.match(play, /_valley\.size_px/);
  assert.match(play, /_valley\.visible = zone == "valley"/);
  assert.match(play, /_paint_fish/);
  assert.match(play, /_show_zone/);
  assert.match(play, /zone_map/);
  assert.doesNotMatch(play, /prop-cover-|prop-hut|prop-lodge/);
  const bedPaint = readFileSync("tools/paint_valley_bed.py", "utf8");
  assert.match(bedPaint, /Hard-replace the pair|landscape corridor|valley-path-fill/);
  const srcFiles = ["src/sim/world.ts", "src/scenes/look.test.ts"];
  for (const p of srcFiles) {
    const src = readFileSync(p, "utf8");
    assert.doesNotMatch(src, /bed-valley/);
  }
});

test("Godot two phones share a shout, a map, and a seat", () => {
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /_paint_mate/);
  assert.match(play, /断线了，人还在原地/);
  assert.match(play, /还没来/);
  assert.match(play, /partnerAt/);
  assert.match(play, /_atlas_flash/);
  assert.match(play, /mate_ping|partner.*ping/);
  assert.doesNotMatch(play, /等另一部|空等|waitingFortune/);
  const actor = readFileSync("godot/scripts/actor_view.gd", "utf8");
  assert.match(actor, /ping_glow/);
  assert.match(actor, /away/);
  assert.match(actor, /ping > 0/);
  assert.doesNotMatch(actor, /Wilson|Don't Starve|Dont Starve/i);
  const look = readFileSync("godot/scripts/look.gd", "utf8");
  assert.match(look, /ping_glow/);
  assert.match(look, /ping_tex/);
  assert.match(look, /0\.96, 0\.90, 0\.78/);
  const world = readFileSync("src/sim/world.ts", "utf8");
  assert.match(world, /away: this\.away\.has/);
  assert.match(world, /present\(\)/);
  assert.match(world, /reclaim\(/);
  assert.match(world, /this\.near\(/);
});

test("Godot ear is five thin sounds and one mute that does not change the world", () => {
  assert.ok(existsSync("godot/scripts/ear.gd"));
  const ear = readFileSync("godot/scripts/ear.gd", "utf8");
  assert.match(ear, /class_name ValleyEar/);
  assert.match(ear, /step/);
  assert.match(ear, /shore/);
  assert.match(ear, /fire/);
  assert.match(ear, /door/);
  assert.match(ear, /green/);
  assert.match(ear, /muted/);
  assert.match(ear, /unlock/);
  assert.match(ear, /0\.38/);
  assert.match(ear, /0\.72/);
  assert.match(ear, /does not touch the world|不改规则|does not change the world/);
  assert.doesNotMatch(ear, /Net\.send|send_input|send_take/);
  assert.doesNotMatch(ear, /Wilson|Don't Starve|Dont Starve/i);
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /ValleyEar/);
  assert.match(play, /_ear\.hear/);
  assert.match(play, /_toggle_mute/);
  assert.match(play, /"声"/);
  assert.match(play, /"静"/);
  assert.doesNotMatch(play, /send_.*mute|muted.*send/);
  assert.doesNotMatch(play, /Wilson|Don't Starve|Dont Starve/i);
});

test("Godot evening walk is fish, pot, then a night rest", () => {
  assert.ok(existsSync("godot/scripts/headless_evening_loop.gd"));
  const evening = readFileSync("godot/scripts/headless_evening_loop.gd", "utf8");
  assert.match(evening, /FISH_OK/);
  assert.match(evening, /COOK_OK/);
  assert.match(evening, /DAY_REST_NO/);
  assert.match(evening, /SLEEP_OK/);
  assert.match(evening, /EVENING_OK/);
  assert.match(evening, /get_ticks_msec/);
  assert.doesNotMatch(evening, /Wilson|Don't Starve|Dont Starve/i);
});
