import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { test } from "node:test";

test("Godot 4 project is the playable client", () => {
  const proj = readFileSync("godot/project.godot", "utf8");
  assert.match(proj, /config\/features=PackedStringArray\("4\.3"/);
  assert.match(proj, /default_texture_filter=1/);
  assert.match(proj, /run\/main_scene="res:\/\/scenes\/main\.tscn"/);
  assert.ok(existsSync("godot/scenes/main.tscn"));
  assert.ok(existsSync("godot/scripts/net.gd"));
  assert.ok(existsSync("godot/assets/art/char-warm.png"));
  assert.ok(existsSync("godot/assets/art/char-pine.png"));
  assert.ok(existsSync("godot/assets/art/tex-grass.png"));
  const charter = readFileSync("docs/CHARTER.md", "utf8");
  assert.match(charter, /引擎已定为 Godot 4/);
  assert.match(charter, /不再等网页打磨/);
  assert.match(charter, /不用 Unity/);
  assert.doesNotMatch(charter, /Capacitor/);
});

test("Godot HTML5 export is what phones open", () => {
  assert.ok(existsSync("godot/export/web/index.html"));
  const html = readFileSync("godot/export/web/index.html", "utf8");
  assert.match(html, /并肩山谷/);
  assert.match(html, /<canvas/);
  assert.match(html, /Engine/);
  assert.doesNotMatch(html, /\$GODOT_/);
  assert.ok(existsSync("godot/export/web/index.wasm"));
  assert.ok(existsSync("godot/export/web/index.pck"));
  assert.ok(existsSync("godot/export/web/index.js"));
});

test("Valley look is one dusk illustration, not DST stickers", () => {
  assert.ok(existsSync("godot/fonts/kai.ttf"));
  assert.ok(existsSync("godot/assets/art/cover-valley.png"));
  assert.ok(existsSync("godot/assets/art/ground-valley.png"));
  const look = readFileSync("godot/scripts/look.gd", "utf8");
  assert.match(look, /kai\.ttf/);
  assert.match(look, /multiply\.ttf/);
  assert.match(look, /tex-plaque/);
  assert.match(look, /contact\(/);
  assert.match(look, /sit_frac/);
  assert.match(look, /person_mat/);
  assert.match(look, /const BODY := 62/);
  assert.match(look, /const FOOT := 0\.979/);
  assert.match(look, /name_box/);
  assert.match(look, /set_shader_parameter\("grade", 0\.0\)/);
  assert.doesNotMatch(look, /SystemFont/);
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /_clamp_cam/);
  assert.match(play, /_cam_locked/);
  assert.match(play, /%s×%s/);
  assert.match(play, /1\.0, 1\.0, 1\.0/);
  assert.ok(existsSync("godot/fonts/multiply.ttf"));
  const actor = readFileSync("godot/scripts/actor_view.gd", "utf8");
  assert.match(actor, /CanvasLayer/);
  assert.match(actor, /_place_name/);
  assert.match(actor, /person_mat/);
  assert.match(actor, /Look\.BODY/);
  assert.match(actor, /Look\.FOOT/);
  assert.doesNotMatch(actor, /var h := 48/);
  const lookShot = readFileSync("godot/scripts/headless_look.gd", "utf8");
  assert.match(lookShot, /cabin-pair/);
  assert.match(lookShot, /set_moving/);
  const boot = readFileSync("godot/scripts/boot.gd", "utf8");
  assert.match(boot, /cover-valley/);
  assert.doesNotMatch(boot, /prop-cabin|prop-inn|Wanderer/);
  const room = readFileSync("godot/scripts/room.gd", "utf8");
  assert.match(room, /cover-valley/);
  assert.doesNotMatch(room, /char-warm|char-pine|Wanderer/);
  const valley = readFileSync("godot/scripts/valley_map.gd", "utf8");
  assert.match(valley, /ground-valley/);
  assert.match(valley, /prop-hut|prop-lodge/);
  assert.match(valley, /floor-valley/);
  assert.match(valley, /_bend\(/);
  assert.match(valley, /_bend\(4\.2, "creek"\) - 0\.82/);
  assert.doesNotMatch(valley, /band-river|band-path|band-meadow/);
  const floorPaint = readFileSync("tools/paint_valley_sit.py", "utf8");
  assert.match(floorPaint, /308\.0 \+ fx \* 82\.0/);
  assert.match(floorPaint, /0\.16, 0\.42, 0\.52/);
  assert.doesNotMatch(floorPaint, /g \/ np\.maximum\(g\.max/);
  assert.ok(existsSync("godot/assets/art/floor-valley.png"));
  assert.doesNotMatch(valley, /_tile\(/);
  assert.doesNotMatch(valley, /prop-cabin|prop-inn/);
  assert.doesNotMatch(play, /modulate = Color\(1, 1, 1, 0\.55\)/);
  const scripts = ["boot.gd", "room.gd", "play.gd", "look.gd", "valley_map.gd", "actor_view.gd", "ear.gd"]
    .map((n) => readFileSync(`godot/scripts/${n}`, "utf8"))
    .join("\n");
  assert.doesNotMatch(scripts, /Wanderer|Wilson|Don't Starve|Dont Starve/i);
  const inn = readFileSync("godot/assets/art/prop-inn.png");
  assert.ok(!inn.includes("Wanderer") && !inn.includes("WANDERER") && !inn.includes("Good Ale"));
  assert.ok(existsSync("godot/assets/art/prop-anvil.png"));
  assert.ok(existsSync("godot/assets/art/prop-altar.png"));
  const sync = readFileSync("godot/tools/sync_art.sh", "utf8");
  assert.match(sync, /keeping godot\/assets\/art/);
  assert.doesNotMatch(sync, /cp -a/);
  const paint = readFileSync("tools/paint_look.py", "utf8");
  assert.match(paint, /trim_empty_feet/);
  assert.match(paint, /def finish_sit_props/);
  const sit = readFileSync("tools/sit_chars.py", "utf8");
  assert.match(sit, /char-warm-ref/);
  assert.match(sit, /FOOT_Y/);
  assert.match(sit, /BAN/);
  assert.doesNotMatch(sit, /SRCS\[.*= .*walk-raw/);
  const warmWalk = readFileSync("godot/assets/art/char-warm-walk.png");
  assert.ok(!warmWalk.includes("Wilson") && !warmWalk.includes("WANDERER"));
});

test("Godot client plays fish, mine and kitchen from the same snap", () => {
  assert.ok(existsSync("godot/scripts/zone_map.gd"));
  assert.ok(existsSync("godot/scripts/headless_loop.gd"));
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /toasts/);
  assert.match(play, /send_take/);
  assert.match(play, /_bag_sig/);
  assert.match(play, /_ink_n/);
  assert.match(play, /_paint_fish/);
  assert.match(play, /Look\.MOSS/);
  assert.match(play, /_tiles = \[\]/);
  assert.match(play, /show_fog/);
  assert.match(play, /biome/);
  assert.match(play, /fires/);
  const actor = readFileSync("godot/scripts/actor_view.gd", "utf8");
  assert.match(actor, /fishMark|fish_mark/);
  assert.match(actor, /char-%s-fish/);
  assert.match(actor, /Look\.MOSS/);
  assert.match(actor, /_bar_pull/);
  const look = readFileSync("godot/scripts/look.gd", "utf8");
  assert.match(look, /const MOSS/);
  const zone = readFileSync("godot/scripts/zone_map.gd", "utf8");
  assert.match(zone, /ch == "#"/);
  assert.match(zone, /show_fog/);
  assert.match(zone, /ch == "F"/);
  assert.match(zone, /ch == "J"/);
  const net = readFileSync("godot/scripts/net.gd", "utf8");
  assert.match(net, /revealed/);
  const world = readFileSync("src/sim/world.ts", "utf8");
  assert.match(world, /先面向要做的事/);
  assert.match(world, /先面向树、火或能砍的/);
  assert.match(world, /手里没有能切的/);
  assert.doesNotMatch(world, /if \(!p\.input\.held\) return;/);
  const loop = readFileSync("godot/scripts/headless_loop.gd", "utf8");
  assert.match(loop, /FISH_OK/);
  assert.match(loop, /ORE_OK/);
  assert.match(loop, /PLATE_OK/);
  assert.ok(existsSync("godot/scripts/headless_cover_loop.gd"));
  const coverLoop = readFileSync("godot/scripts/headless_cover_loop.gd", "utf8");
  assert.match(coverLoop, /COVER_LOOP_OK/);
  assert.match(coverLoop, /show_room|开一间/);
  assert.match(coverLoop, /if ore_ok:/);
  assert.match(loop, /if ore_ok:/);
  assert.match(loop, /send_acc/);
  assert.match(loop, /quit\(0\)[\s\S]{0,20}return/);
  assert.ok(existsSync("godot/scripts/headless_rest_loop.gd"));
  const rest = readFileSync("godot/scripts/headless_rest_loop.gd", "utf8");
  assert.match(rest, /WILD_OK/);
  assert.match(rest, /FORGE_OK/);
  assert.match(rest, /STALL_OK/);
  assert.doesNotMatch(rest, /Wilson|Don't Starve|Dont Starve/i);
  assert.ok(existsSync("godot/scripts/headless_village_loop.gd"));
  const village = readFileSync("godot/scripts/headless_village_loop.gd", "utf8");
  assert.match(village, /FIELD_OK/);
  assert.match(village, /FORTUNE_OK/);
  assert.match(village, /BOARD_OK/);
  assert.match(village, /DAY_REST_NO/);
  assert.match(village, /SLEEP_OK/);
  assert.match(village, /HARVEST_OK/);
  assert.match(village, /show_crops/);
  assert.doesNotMatch(village, /Wilson|Don't Starve|Dont Starve/i);
  assert.doesNotMatch(village, /waitingFortune|另一部手机/);
});

test("Godot village shows crops, fortune and the dawn board from the same snap", () => {
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /_paint_signs/);
  assert.match(play, /_paint_crops/);
  assert.match(play, /show_crops/);
  assert.match(play, /今晚/);
  assert.match(play, /fortune/);
  assert.match(play, /熟了/);
  assert.doesNotMatch(play, /waitingFortune/);
  assert.doesNotMatch(play, /另一部手机|必须两/);
  const valley = readFileSync("godot/scripts/valley_map.gd", "utf8");
  assert.match(valley, /show_crops/);
  assert.match(valley, /prop-tuft|prop-bush/);
  assert.doesNotMatch(valley, /prop-cabin|prop-inn/);
  const world = readFileSync("src/sim/world.ts", "utf8");
  assert.match(world, /没有种。田不用浇/);
  assert.match(world, /也得对着铺/);
  assert.match(world, /还早。天黑再歇/);
  assert.match(world, /一个人能问|问今日/);
});

test("Godot two phones share a shout, a map, and a seat", () => {
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /_paint_mate/);
  assert.match(play, /断线了，人还在原地/);
  assert.match(play, /还没来/);
  assert.match(play, /partnerAt/);
  assert.match(play, /_atlas_flash/);
  assert.match(play, /mate_ping|partner.*ping/);
  assert.doesNotMatch(play, /等另一部|空等|waitingFortune/);
  const actor = readFileSync("godot/scripts/actor_view.gd", "utf8");
  assert.match(actor, /ping_glow/);
  assert.match(actor, /away/);
  assert.match(actor, /ping > 0/);
  assert.doesNotMatch(actor, /Wilson|Don't Starve|Dont Starve/i);
  const look = readFileSync("godot/scripts/look.gd", "utf8");
  assert.match(look, /ping_glow/);
  assert.match(look, /ping_tex/);
  assert.match(look, /0\.96, 0\.90, 0\.78/);
  const world = readFileSync("src/sim/world.ts", "utf8");
  assert.match(world, /away: this\.away\.has/);
  assert.match(world, /present\(\)/);
  assert.match(world, /reclaim\(/);
  assert.match(world, /this\.near\(/);
});

test("Godot ear is five thin sounds and one mute that does not change the world", () => {
  assert.ok(existsSync("godot/scripts/ear.gd"));
  const ear = readFileSync("godot/scripts/ear.gd", "utf8");
  assert.match(ear, /class_name ValleyEar/);
  assert.match(ear, /step/);
  assert.match(ear, /shore/);
  assert.match(ear, /fire/);
  assert.match(ear, /door/);
  assert.match(ear, /green/);
  assert.match(ear, /muted/);
  assert.match(ear, /unlock/);
  assert.match(ear, /0\.38/);
  assert.match(ear, /0\.72/);
  assert.match(ear, /does not touch the world|不改规则|does not change the world/);
  assert.doesNotMatch(ear, /Net\.send|send_input|send_take/);
  assert.doesNotMatch(ear, /Wilson|Don't Starve|Dont Starve/i);
  const play = readFileSync("godot/scripts/play.gd", "utf8");
  assert.match(play, /ValleyEar/);
  assert.match(play, /_ear\.hear/);
  assert.match(play, /_toggle_mute/);
  assert.match(play, /"声"/);
  assert.match(play, /"静"/);
  assert.doesNotMatch(play, /send_.*mute|muted.*send/);
  assert.doesNotMatch(play, /Wilson|Don't Starve|Dont Starve/i);
});

test("Godot evening walk is fish, pot, then a night rest", () => {
  assert.ok(existsSync("godot/scripts/headless_evening_loop.gd"));
  const evening = readFileSync("godot/scripts/headless_evening_loop.gd", "utf8");
  assert.match(evening, /FISH_OK/);
  assert.match(evening, /COOK_OK/);
  assert.match(evening, /DAY_REST_NO/);
  assert.match(evening, /SLEEP_OK/);
  assert.match(evening, /EVENING_OK/);
  assert.match(evening, /get_ticks_msec/);
  assert.doesNotMatch(evening, /Wilson|Don't Starve|Dont Starve/i);
});
